[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  ENVIRONMENT = "production"

# Redirects for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 