version: '3'
services:
  colyseus:
    build: .
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    command: npm start
    restart: always

volumes:
  app-data: 